### ISSUE TITLE
FEATURE REQUEST: IRONFISH support

### ISSUE THREAD

**Issue by isezen** [KaffinPX/KStratum#13]
Hello,

is it possible to modify/improve the KStratum to work with [IRONFISH node](https://github.com/iron-fish/ironfish/wiki/Getting-Started#5-start-mining---you-can-mine-solo-or-in-a-pool)?
Hence, perhaps someone can use a miner with BLAKE3 algo to solo mine iron fish.

Thanks,

**Comment by KaffinPX** [comment]
KStratum was only made for Kaspa.
