### ISSUE TITLE
can not connect outside miner

### ISSUE THREAD

**Issue by randomnodes** [KaffinPX/KStratum#15]
Can connect locally, but cant connect from same network. Is there a line of code that needs to be added to allow outside connections?

Also, I am receiving jobs on miner side, but no info showing after "stratum server listening" is this expected? no connection/disconnection outside devices? Hash rate? Etc?

**Comment by KaffinPX** [comment]
You should set ``--listen-address`` to 0.0.0.0 for allowing outside connections or use a proxy like Nginx.
Yes, not so logging rn.
