### ISSUE TITLE
Issue with JS

### ISSUE THREAD

**Issue by jgonzis** [KaffinPX/KStratum#4]
Hi, 

I hope that image could help you.

![image](https://user-images.githubusercontent.com/38668405/182456701-a9c6b56f-1061-42ac-9473-bdf32a0745c0.png)

**Comment by JeanOUINA** [comment]
Hi, sorry we've just updated the kaspajs library and @KaffinPX introduced a breaking change. I've just published a new version, this one should work without any issue.
